version: "3.8"

services:
  home:
    build: ./home
    ports:
<<<<<<< Updated upstream
      - "5000:5000"
=======
      - "5001:5000"
>>>>>>> Stashed changes
    volumes:
      - ./home:/usr/src/app
    env_file:
      - ./database_postgresql/base.env
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

<<<<<<< Updated upstream
  administrador:
    build: ./administrador
    ports:
      - "5002:5000"
    volumes:
      - ./administrador:/usr/src/app
=======
  admin:
    build: ./Administrador
    ports:
      - "5002:5000"
    volumes:
      - ./Administrador:/usr/src/app
>>>>>>> Stashed changes
    env_file:
      - ./database_postgresql/base.env
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
<<<<<<< Updated upstream
    image: postgres:latest
    container_name: postgres_db
=======
    image: postgres:latest  # Esta es la forma correcta de usar 'image'
>>>>>>> Stashed changes
    env_file:
      - ./database_postgresql/base.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database_postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

<<<<<<< Updated upstream
volumes:
  db_data:
=======
networks:
  sanamed_network:
    driver: bridge

volumes:
  inicio_data:
    driver: local
>>>>>>> Stashed changes
